### ISSUE TITLE
リリースv0.1.1の詳細ページに選択肢が表示されません

### ISSUE THREAD

**Issue by tyanio** [jphacks/D_2001#93]
## 概要
今のところ自分はリリースの詳細ページに選択肢が表示されないです…
ログインなどはできています
自分の環境だけなのかひとまず確認していただきたいです！

コンソールには以下のエラーが出ております
![2020-11-05](https://user-images.githubusercontent.com/19584781/98200911-f5c49a00-1f71-11eb-878a-72fb54bdb1cb.png)

**Comment by Yamakatsu63** [comment]
@tyanio 
バグを修正したのでレビューお願いします
[PRリンク](https://github.com/jphacks/D_2001/pull/94)
