### ISSUE TITLE
詳細ページでリロードやURLを踏むと404になっちゃいます

### ISSUE THREAD

**Issue by tyanio** [jphacks/D_2001#98]
## 概要
原因不明…Localhostでは動きます
共有リンクを生成したいために一意URLを導入したのですが、結局URLを共有できない状態ですので割とFatalなバグですね…

**Comment by ghost** [comment]
URLからparameterを取得することができないのでは？
link_toでparameterを渡しているため初回アクセス時のみしかparameterを習得できない？

**Comment by kugimasa** [comment]
https://router.vuejs.org/guide/essentials/dynamic-matching.html#reacting-to-params-changes
